config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

 resources :blogs
 post 'blogs/new'
 get 'blogs/index'
 resources :users, only: [:new, :create, :show]
 resources :blogs, only: [:new, :create, :edit, :destroy]
 resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :users
   root to: 'sessions#new'
  resources :blogs
  
 
 
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, length: { in: 1..140 }
    validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
   validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  
           format:{ with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
           before_save { email.downcase! }
 validates :password, length: { minimum: 6 }
 #has_secure_password
  
  has_secure_password  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  protect_from_forgery with: :exception
  include SessionsHelper
  include BlogsHelper
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
   before_action :set_blog, only: [:show, :edit, :update, :destroy] 
  
  
  def index
    @blogs = Blog.all
  end

  # Add
  def new
  if params[:back]
      @blog = Blog.new(blog_params)
    else
       @blog = Blog.new    
  end
  
  end
  def create
     
     @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      # Switch to the list screen and display a message saying "You have created new blog!"
      redirect_to blogs_path, Notice: "You have created new blog!"
    else
      # Redraw the input form.
      render 'new'
    end
  end
  def show
    # 追記する
     @blogs = Blog.find(params[:id])
  end
  def edit
     @blogs = Blog.find(params[:id])
  end
    
    def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "You have edited this blog！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blogs.destroy
    redirect_to blogs_path, Notice: "You have deleted the blog!"
  end
  
  

  #Omitted
  private
  #Before_action : Set_blog, only: [:show, :edit, :update, :destroy] 
   def blog_params
    params.require(:blog).permit(:title, :content)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
end  
  #Omission
  
  #Omission
  #Omitted

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      # if login succeeds
    else
      flash[:danger] = 'Login failed'
      render 'new'
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authenticate_user!, :except => [:show, :index]
 def index
    @user = User.all
    
 end
 def new
    @user = User.new
     
 end
 
 def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
 end
 def show
    @user = User.find(params[:id])
    

 end
 def edit
     @user = User.find(params[:id])
 end
 def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path, Notice: "You have edited this user！"
      else
        render 'edit'
      end
 end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def force_login
      if !logged_in?
      redirect_to sessions_path
      end
  end
    
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blogs.errors.count %>errors occurred.</h2>
      <ul>

      <% @blogs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "Return to List of blogs screen", blogs_path %>

app/views/blogs/destroy.html.erb
<%= form_with(model: @blogs, local: true) do |form| %>
<div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <h2>Create a new blog</h2>

  
  <%= form.submit %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blogs, local: true) do |form| %>
<div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <h2>Create a new blog</h2>

  
  <%= form.submit %>
<% end %>

app/views/blogs/index.html.erb
<h1>List of blogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Contents</th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
   <td><%= link_to 'Check the details', blog_path(blog.id) %></td>
       <% if current_user.id == blog.user_id %>
    <td><%= link_to "Edit this blog", edit_blog_path(blog.id) %></td>
 
    
  <td>  <%= link_to 'Post a new blog', new_blog_path %></td>
  </tr>
<% end %>
<% end %>

  
  
</table>

<br>

app/views/blogs/new.html.erb
<h2>New post</h2>

  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>blog Detail Screen </h1>
<p>Title: <%= @blogs.title %></p>
<p>Contents: <%= @blogs.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Augustin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
     <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% @user = current_user %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    
  
<%= yield %>

  <footer>
    
    <p>© 2015-2016 Copyright AUGUSTIN Corp.</p>
  </footer>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>errors occurred.</h2>
      <ul>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Edit my account" %>
<% end %>

app/views/users/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bootstrap</a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
        <li><a href="">menu2</a></li>
      </ul>
      
  </div>
    </div>
    
    
</nav>

<div class="container">
    
    
    <article>
        <div class="contents">
            <ul class="row">
    <li class="col-md-offset-1 col-md-6">contents1</li>
    <li class="col-md-offset-2 col-md-6">contents2</li>
    
</ul>
        </div>
        
    </article>
    
</div>

</table>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s page</h1>

<p>email address: <%= @user.email %></p>

    
  <% user = current_user %>
  <% if logged_in? %>
   <%= link_to 'Check the details', user_path %>
   <%= link_to "Edit this blog", edit_user_path %>
  
  </tr>
 
<%= link_to 'Post a new blog', new_blog_path%>
<% end %>
    